dist: trusty
sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy-5.7.1     # Python 2.7 compatible
  - pypy3.5-5.8.0  # Python 3.5 compatible
matrix:
  include:
    - python: 2.7
      env:
        - JYTHON_VERSION=2.7.0
        - JYTHON_SHASUM=b08d73b5df7d95e35e7b8dcaf1558025cf24f0f1
        - TOX_ENV=jython
    - python: 3.4
      env:
        - TOX_ENV=flake8

before_install:
    - if [ `uname -m` == "x86_64" ] || [ `uname -m` == "amd64" ]; then export ARCH="amd64"; else export ARCH="386"; fi
    - export PLATFORM=`uname -s | tr '[:upper:]' '[:lower:]'`
    - export VAULT_URL="https://releases.hashicorp.com/vault/0.6.1/vault_0.6.1_${PLATFORM}_${ARCH}.zip"
    - mkdir -p $HOME/bin

install:
    - curl -fSL -tlsv1 -o vault.zip $VAULT_URL && unzip -o vault.zip && mv vault $HOME/bin && rm vault.zip
    - if [ -n "$JYTHON_VERSION" ]; then export JYTHON_URL="http://search.maven.org/remotecontent?filepath=org/python/jython-installer/${JYTHON_VERSION}/jython-installer-${JYTHON_VERSION}.jar"; fi
    - if [ -n "$JYTHON_VERSION" ]; then curl -fSL -o jython_installer.jar $JYTHON_URL && echo "$JYTHON_SHASUM *jython_installer.jar" | shasum -c - && java -jar jython_installer.jar -s -d $HOME/jython && rm jython_installer.jar; fi

before_script:
    - pip install -U setuptools
    - pip install -U pip tox python-coveralls
    - pip freeze --all
    - if [ -n "$JYTHON_VERSION" ]; then export PATH=$HOME/jython/bin:$PATH; fi
    - tox -e setup

script:
    - if [ -z "$TOX_ENV" ]; then export TOX_ENV=py; fi
    - tox -e $TOX_ENV

after_success:
    - coveralls -i -d reports/coverage-*.dat
