dist: xenial
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy        # Python 2.7 compatible
  - pypy3.5     # Python 3.5 compatible
  - pypy3       # Python 3.6 compatible
matrix:
  include:
    - python: 2.7
      env:
        - JYTHON_VERSION=2.7.1
        - TOX_ENV=jython
    - python: 3.7
      env:
        - TOX_ENV=flake8

before_install:
    - if [ `uname -m` == "x86_64" ] || [ `uname -m` == "amd64" ]; then export ARCH="amd64"; else export ARCH="386"; fi
    - export PLATFORM=`uname -s | tr '[:upper:]' '[:lower:]'`
    - export VAULT_URL="https://releases.hashicorp.com/vault/0.6.1/vault_0.6.1_${PLATFORM}_${ARCH}.zip"
    - echo $PATH

install:
    - curl -fSL -tlsv1 -o vault.zip $VAULT_URL && unzip -o vault.zip && mv vault $HOME/bin && rm vault.zip
    - if [ -n "$JYTHON_VERSION" ]; then pyenv install jython-$JYTHON_VERSION; pyenv global jython-$JYTHON_VERSION; pyenv rehash; fi
    - pip install -U setuptools pip
    - pip install -U 'tox<3.10.0' python-coveralls
    - pip freeze --all
    - if [ -n "$JYTHON_VERSION" ]; then export "PATH=/opt/pyenv/shims:$PATH"; fi
    - pyenv version; python --version; which python; which jython; which pip

before_script:
    - tox -e setup

script:
    - if [ -z "$TOX_ENV" ]; then export TOX_ENV=py; fi
    - tox -e $TOX_ENV

after_success:
    - coveralls -i -d reports/coverage-*.dat
